
const Data = [
    {
      id: "1",
      title: "Darjeeling Tour",
      category: "Hillstations",
      img: "https://tse2.mm.bing.net/th?id=OIP.APtZTwWPLoz5A__ALdJeSwHaEK&pid=Api&P=0&h=180",
      desc1: "Starting from Rs=8000/-",
      desc2:"5 nights-6 days",
    },
    {
        id: "2",
        title: "Himachal Tour",
        category: "Hillstations",
        img: "https://static.toiimg.com/photo/msid-93246451,width-96,height-65.cms",
        desc1: "Starting from Rs=20000/-",
        desc2:"15 nights-16 days",
    },
    {
        id: "3",
        title: "Sikkim Tour",
        category: "Hillstations",
        img: "https://images.unsplash.com/photo-1551155311-88cda3ebe650?ixlib=rb-1.2.1&auto=format&fit=crop&w=962&q=80",
        desc1: "Starting from Rs=15000/-",
        desc2:"9 nights-10 days",
    },
    {
        id: "4",
        title: "Dehradun-Mussorie Tour",
        category: "Hillstations",
        img: "https://tse4.mm.bing.net/th?id=OIP.5ybYEZlD2xqApXfPVutAEQHaC5&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=20000/-",
        desc2:"12 nights-13 days",
    },
    {
      id: "5",
      title: "Goa Tour",
      category: "Beachside",
      img: "https://tse2.mm.bing.net/th?id=OIP.3xvfms5y9MN3n4EFioARmAHaEK&pid=Api&P=0&h=180",
      desc1: "Starting from Rs=15000/-",
      desc2:"4 nights-5 days",
    },
    {
      id: "6",
      title: "Andaman-Lakshadeep Tour",
      category: "Beachside",
      img: "https://tse4.mm.bing.net/th?id=OIP.USV4QZM-Nu9CmKJpUFh6pAHaEo&pid=Api&P=0&h=180",
      desc1: "Starting from Rs=25000/-",
      desc2:"15 nights-16 days",
    },
    {
      id: "7",
      title: "Kerala Tour",
      category: "Beachside",
      img: "https://www.tourmyindia.com/blog/wp-content/uploads/2021/03/Best-Places-to-Visit-in-Kerala.jpg",
      desc1: "Starting from Rs=18000/-",
      desc2:"11 nights-12 days",
    },
    {
      id: "8",
      title: "Maldives Tour",
      category: "Beachside",
      img: "https://tse3.mm.bing.net/th?id=OIP.Ub-kAO7W88FFh0126K2pZwHaE8&pid=Api&P=0&h=180",
      desc1: "Starting from Rs=30000/-",
      desc2:"9 nights-10 days",
    },
    {
        id: "9",
        title: "12 Jyotirlinga Tour",
        category: "Pilgrimage",
        img: "https://tse1.mm.bing.net/th?id=OIP.cr8uGYHcwzf9gmKm_wosIgHaEK&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=30000/-",
        desc2:"19 nights-20 days",
      },
      {
        id: "10",
        title: "Chardham Yatra Tour",
        category: "Pilgrimage",
        img: "https://tse1.mm.bing.net/th?id=OIP.pOKpkt9uuVPD7TTL9U8S6wHaFJ&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=35000/-",
        desc2:"19 nights-20 days",
      },
      {
        id: "11",
        title: "South Indian Temple Tour",
        category: "Pilgrimage",
        img: "https://tse4.mm.bing.net/th?id=OIP.2TNjiS8Z8N3iqsUCHAiOWgHaE8&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=20000/-",
        desc2:"11 nights-12 days",
      },
      {
        id: "12",
        title: "Jain & Buddhist Temple Tour",
        category: "Pilgrimage",
        img: "https://tse4.mm.bing.net/th?id=OIP.IMQJ2jzjr5U1QdH1gfRzCwHaE8&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=15000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "13",
        title: "Delhi & Agra Tour",
        category: "Heritage",
        img: "https://tse3.mm.bing.net/th?id=OIP.lNMIK5As0Mp7nyVA_aVkWQHaE_&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=16000/-",
        desc2:"11 nights-12 days",
      },
      {
        id: "14",
        title: "Rajasthan  Heritage Tour",
        category: "Heritage",
        img: "https://indiatrekkingtours.com/wp-content/uploads/2022/02/rajasthan.jpg",
        desc1: "Starting from Rs=20000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "15",
        title: "Gujrat Heritage Tour",
        category: "Heritage",
        img: "https://4.bp.blogspot.com/-TRwIMOtX4H0/VsrgCseU5BI/AAAAAAAAAb0/bMo5FIBld3Q/s1600/heritages.jpg",
        desc1: "Starting from Rs=16000/-",
        desc2:"14 nights-15 days",
      },
      {
        id: "16",
        title: "Khajurao Madhyapradesh Tour",
        category: "Heritage",
        img: "https://tse4.explicit.bing.net/th?id=OIP.4bIzAxm20ZvVV0xOePx0dQHaFj&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=18000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "17",
        title: "Sundarban Tour",
        category: "Wildlife",
        img: "https://mangroveactionproject.org/wp-content/uploads/2024/11/Soham-Bhattacharyya-India-Winter-Morning-Mangroves-The-Royal-Bengal-Tiger-1024x683.jpg",
        desc1: "Starting from Rs=10000/-",
        desc2:"9 nights-10 days",
      },
      {
        id: "18",
        title: "Dooars Tour",
        category: "Wildlife",
        img: "https://tse1.mm.bing.net/th?id=OIP.6-VO7jxsLO0nd8hqFrr8QwHaEn&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=15000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "19",
        title: "Madhyapradesh Wildlife Tour",
        category: "Wildlife",
        img: "https://www.pugdundeesafaris.com/blog/wp-content/uploads/2017/06/Kanha-National-Park-1024x576.jpg",
        desc1: "Starting from Rs=14000/-",
        desc2:"9 nights-10 days",
      },
      {
        id: "20",
        title: "Nepal Wildlife Tour",
        category: "Wildlife",
        img: "https://tse1.mm.bing.net/th?id=OIP.RJAKIh43vqBi6TxKOFrdJwHaF6&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=20000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "21",
        title: "Paris Tour",
        category: "International",
        img: "https://tse1.mm.bing.net/th?id=OIP.t_vWsJPCf9pGLarIHpP7eQHaEo&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=95000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "22",
        title: "London Tour",
        category: "International",
        img: "https://tse1.mm.bing.net/th?id=OIP.PnJ-7XFTf9ejInPJHebRxgHaEo&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=92000/-",
        desc2:"9 nights-10 days",
      },
      {
        id: "23",
        title: "New York Tour",
        category: "International",
        img: "https://tse4.mm.bing.net/th?id=OIP.TaC_bMKPpttjJP-7Ehu80gHaEW&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=95000/-",
        desc2:"15 nights-16 days",
      },
      {
        id: "24",
        title: "Norway Tour",
        category: "International",
        img: "https://tse1.mm.bing.net/th?id=OIP.HMlmydC58r6CAXkPFC_5ngHaE8&pid=Api&P=0&h=180",
        desc1: "Starting from Rs=90000/-",
        desc2:"15 nights-16 days",
      },
     
   
  ];
   
  export default Data;
